### PR TITLE
Experiment no 2

### PR DESCRIPTION
**Pull request by pinglinh**
| Section | Details |
| --- | --- |
| Type | Idea |
| Title | Centering Intro Video and Text |
| Description | I thought it would be better that the intro video and text is centered for more impact when users visit the site. This could make them more likely to click on the video and read the intro so that they know what the website is about. |
| Screenshot | Include? Yes |
# See screenshots below
## 1. Video

screen shot 2016-08-07 at 17 16 18
## 2. Text

screen shot 2016-08-07 at 17 16 27

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thank you for the Pull Request @pinglinh !! 👍 

I prefer the Introduction info not centred & the video next to the text as it takes up less space on the screen. However, I do like your idea of making the video bigger.

Can we try just to make the video bigger & see how that looks? Thanks 😄

**Comment by pinglinh** [comment]
Hi Eddie! So sorry it took me so long to get back to this pull request! But as requested I changed it to how you preferred it to be :bowtie: 

I have made the video bigger 📹  but let me know if you want it smaller than this :rabbit: (sorry just testing out emojis for GitHub :grin:)

**Comment by eddiejaoude** [comment]
No worries at all. Thank you for the PR! 👍

**Comment by eddiejaoude** [comment]
Looks great, thanks @pinglinh 👍 

screenshot 2016-08-23 07 56 43

**Pull request merged**
